name: Run Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install packages
        run: pip install -r requirements.txt
      - name: run unit tests
        run: python -m unittest tests/test_readme_level.py
